services:
  server:
    build: srv
    volumes:
      - .:/go/src/simple-worker

    command: >
      /bin/sh -c "cp /go/src/simple-worker/certs/rootCA.crt /etc/ssl/certs/
      && go build srv/server.go
      && ./server"

    ports:
      - 50051:50051

  client1:
    build: clnt
#    volumes:
#      - .:/go/src/simple-worker

    command: >
      /bin/sh -c "cp /go/src/simple-worker/certs/rootCA.crt /etc/ssl/certs/
      && export CLIENT_KEY_PATH=certs/client1.key
      && export CLIENT_CERT_PATH=certs/client1.crt
      && go build clnt/client.go
      && ./client start -c \"echo Client is UP\"
      && tail -f /dev/null"

    depends_on:
      - server

  client2:
    build: clnt
#    volumes:
#      - .:/go/src/simple-worker

    command: >
      /bin/sh -c "cp /go/src/simple-worker/certs/rootCA.crt /etc/ssl/certs/
      && export CLIENT_KEY_PATH=certs/client2.key
      && export CLIENT_CERT_PATH=certs/client2.crt
      && go build clnt/client.go
      && ./client start -c \"echo Client is UP\"
      && tail -f /dev/null"

    depends_on:
      - server
